// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BCard: typeof import('bootstrap-vue-3')['BCard']
    BForm: typeof import('bootstrap-vue-3')['BForm']
    BFormGroup: typeof import('bootstrap-vue-3')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    BNav: typeof import('bootstrap-vue-3')['BNav']
    BNavItem: typeof import('bootstrap-vue-3')['BNavItem']
  }
}
